### ISSUE TITLE
运行不了报错

### ISSUE THREAD

**Issue by lovelyelfpop** [G-T-L/TaoBaoQianDao#1]
`09:28:27.527/E: Wrapped android.content.ActivityNotFoundException: Unable to find explicit activity class {com.taobao.taobao/com.taobao.tao.homepage.MainActivity3}; have you declared this activity in your AndroidManifest.xml? (file:///android_asset/modules/__app__.js#72)
Wrapped android.content.ActivityNotFoundException: Unable to find explicit activity class {com.taobao.taobao/com.taobao.tao.homepage.MainActivity3}; have you declared this activity in your AndroidManifest.xml?
    at file:///android_asset/modules/__app__.js:72:0
    at enterJinBiZhuangYuan (/storage/emulated/0/脚本/TaoBaoQianDao-master/淘宝签到.js:533:0)
    at taoBaoQianDao (/storage/emulated/0/脚本/TaoBaoQianDao-master/淘宝签到.js:52:0)
    at /storage/emulated/0/脚本/TaoBaoQianDao-master/淘宝签到.js:476:0
    at file:///android_asset/modules/__bridges__.js:10:0`

**Comment by G-T-L** [comment]
这个脚本挺早之前写着玩的   现在淘宝更新了可能就不太好使了  写的也不太好  如果刚入门有兴趣的话可以稍微看下吧
这个错误是淘宝的主界面的活动命变了  从MainActivity3变成MainActivity了  我啥时候抽空再维护下吧

**Comment by G-T-L** [comment]
如果还感兴趣的话可以再尝试下  最近应该是能用的
